version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  pg_m:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
    - postgres_vol_master1:/var/lib/postgresql/data
    - ./ms.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - 6000:5432
  pg_s:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
    - postgres_vol_sla:/var/lib/postgresql/data
    ports:
      - 6001:5432

  adminer:
    image: adminer
    links:
      - pg_m
      - pg_s
    ports:
      - 6004:8080
      
  python-alembic-upgrade:
    build: app/
    depends_on:
      - pg_m
      - pg_s
    command: bash -c "sleep 2 && alembic upgrade head"

  python-worker:
    build: app/
    environment:
      DB_HOST: pg_m
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: pass
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    depends_on:
      - python-alembic-upgrade
      - pg_m
      - rabbitmq
    command: bash -c "sleep 12 && python worker/worker.py"

  python-api:
    build: app/
    environment:
      DB_HOST: pg_m
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: pass
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    depends_on:
      - python-alembic-upgrade
      - pg_m
      - rabbitmq
    command: bash -c "sleep 12 && cd api/ && uvicorn api:app --host=0.0.0.0"

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - python-api
      ports:
        - "8000:8000"

volumes:
  postgres_vol_master1:
  postgres_vol_sla:
  rabbitmq_data:
